name: Windows build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      shell: bash
      env:
        GITHUB_OS: ${{ matrix.os }}
      run: |
        vcpkg install luajit:x64-windows
        vcpkg install sdl2:x64-windows
        echo "C:/vcpkg/installed/x64-windows/tools/luajit" >> $GITHUB_PATH
        echo "C:/vcpkg/installed/x64-windows/share/sdl2" >> $GITHUB_PATH
        echo "C:/vcpkg/installed/x64-windows/bin"   >> $GITHUB_PATH

    - name: Download Submodules
      run: |
        git submodule update --init --recursive --depth=1

    - name: Generate Bindings
      working-directory: cimgui
      shell: bash
      run: |
        cd ./generator
        bash ./generator.sh

    - name: CMake
      run: |
        mkdir cmake-build
        cd cmake-build
        cmake ../cimgui/

    - name: Build
      working-directory: cmake-build
      run: |
        cmake --build . --config Release

    - name: package
      shell: bash
      working-directory: cmake-build
      run: |
        mkdir drop
        cp Release/cimgui.dll drop/
        cp C:/vcpkg/installed/x64-windows/bin/SDL2.dll drop/
        
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: cmake-build/drop/
